version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/web
    environment:
      DATABASE_URL: postgresql://root:password@db:5432/test
    depends_on:
      - db
  db:
    image: postgres:13.1
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
volumes:
  redis:
  db: