version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/src/web
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - db
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
volumes:
  redis:
  db: